In [1]:
from sklearn.datasets import load_iris
from sklearn.tree     import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np


In [3]:
#간단한 머신러닝 구현
import sklearn
print(sklearn.__version__)

0.19.1


# 1. 데이터 로딩

In [6]:
iris= load_iris()
print(type(iris))    #번치 타입
# print(iris.head())   #데이터 프레임이 아니기에 출력 안됨


<class 'sklearn.utils.Bunch'>


In [10]:
keys = iris.keys()
print("dataset keys",keys)  #iris의 키들을 확인

dataset keys dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [18]:
print('key data\n',iris.data)
print('*' * 50)
print('key target\n',iris.target)
print('*' * 50)
print('key target_names\n',iris.target_names)
print('*' * 50)
print('key feature_names\n',iris.feature_names)
print('*' * 50)
print('key DESCR\n',iris.DESCR)
print('*' * 50)

key data
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [

In [19]:
# 피처 데이터세트 확인

iris_data =iris.data
iris_data 

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [20]:
#레이블 (결정값, 타겟,클래스) 데이터 확인
iris_label = iris.target
print(iris_label)
print(iris.target_names)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [38]:
#데이터 프레임으로 변경  /컬럼과 결정값 추가
iris_df =pd.DataFrame(data=iris_data,
                     columns= iris.feature_names)
print(iris_df.head())

iris_df ['target'] = iris_label
print("*"* 100)
display(iris_df.head())


   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
****************************************************************************************************


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [40]:
#학습데이터, 테스트 데이터 분리

X_train,X_test,y_train,y_test=train_test_split(iris_data, iris_label,
                test_size=0.2,
                random_state=20)
print('train data\n', X_train)
print('train label\n', y_train)
print("*"* 50)
print('test data\n', X_test)
print('test label\n', y_test)

train data
 [[5.7 3.  4.2 1.2]
 [5.6 3.  4.1 1.3]
 [5.1 3.5 1.4 0.2]
 [5.1 3.8 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.9 2.5 4.5 1.7]
 [6.  3.4 4.5 1.6]
 [4.9 3.  1.4 0.2]
 [6.4 3.2 4.5 1.5]
 [7.4 2.8 6.1 1.9]
 [5.7 2.8 4.5 1.3]
 [6.1 2.6 5.6 1.4]
 [4.9 3.1 1.5 0.1]
 [6.7 3.1 4.4 1.4]
 [6.3 3.3 4.7 1.6]
 [4.7 3.2 1.3 0.2]
 [5.4 3.9 1.7 0.4]
 [5.  3.3 1.4 0.2]
 [5.7 2.5 5.  2. ]
 [5.1 3.8 1.9 0.4]
 [6.4 2.8 5.6 2.2]
 [6.2 3.4 5.4 2.3]
 [5.4 3.4 1.5 0.4]
 [6.3 3.3 6.  2.5]
 [6.  2.2 4.  1. ]
 [5.6 2.9 3.6 1.3]
 [5.6 3.  4.5 1.5]
 [4.5 2.3 1.3 0.3]
 [5.1 3.4 1.5 0.2]
 [5.5 2.4 3.8 1.1]
 [6.2 2.9 4.3 1.3]
 [5.8 2.6 4.  1.2]
 [5.6 2.5 3.9 1.1]
 [6.7 3.1 4.7 1.5]
 [6.5 2.8 4.6 1.5]
 [5.7 2.9 4.2 1.3]
 [5.1 3.3 1.7 0.5]
 [6.2 2.2 4.5 1.5]
 [6.3 2.3 4.4 1.3]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.4 3.  4.5 1.5]
 [5.5 2.3 4.  1.3]
 [6.1 3.  4.6 1.4]
 [5.1 3.8 1.5 0.3]
 [5.3 3.7 1.5 0.2]
 [6.4 3.2 5.3 2.3]
 [5.5 3.5 1.3 0.2]
 [4.8 3.1 1.6 0.2]
 [5.  2.  3.5 1. ]
 [6.  3.  4.8 1.8]
 [5.8 2.7 5.1 1.9]


In [41]:
#학습을 위한 학습기 - 알고리즘으로 이루어진 객체
iris_dtc =DecisionTreeClassifier(random_state =20)
iris_dtc.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=20,
            splitter='best')

In [42]:
#예측 (predict)수행
prediction = iris_dtc.predict(X_test)
print('y_test\n', y_test)
print('prediction\n', prediction)   #예측한거임

y_test
 [0 1 1 2 1 1 2 0 2 0 2 1 2 0 0 2 0 1 2 1 1 2 2 0 1 1 1 0 2 2]
prediction
 [0 1 1 2 1 1 2 0 2 0 2 1 1 0 0 2 0 1 2 1 1 2 2 0 1 1 1 0 2 1]


In [48]:
#예측 정확도 평가
from sklearn.metrics import accuracy_score
print('예측정확도:{0:.2f}'.format(accuracy_score(y_test, prediction)))

예측정확도:0.93


In [49]:
#데이터 프레임으로 변경  /컬럼과 결정값 추가
iris_df =pd.DataFrame(data=iris_data,
                     columns= iris.feature_names)
print(iris_df.head())

iris_df ['target'] = iris_label
print("*"* 100)
display(iris_df.head())


   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
****************************************************************************************************


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [52]:
#데이터 프레임 형식을 나누는 방법
feature_df=iris_df.iloc[ :,:-1]
display(feature_df.head())


label_df=iris_df.iloc[: ,-1]
display(label_df.head())


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int32

In [56]:
#학습데이터, 테스트 데이터 분리

X_train,X_test,y_train,y_test=train_test_split(feature_df,label_df,
                test_size=0.2,
                random_state=11)
print('train data\n', X_train)
print('train label\n', y_train)
print("*"* 50)
print('test data\n', X_test)
print('test label\n', y_test)
print(type(X_train),type(X_test),type(y_train),type(y_test))


train data
      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
120                6.9               3.2                5.7               2.3
122                7.7               2.8                6.7               2.0
49                 5.0               3.3                1.4               0.2
29                 4.7               3.2                1.6               0.2
118                7.7               2.6                6.9               2.3
105                7.6               3.0                6.6               2.1
77                 6.7               3.0                5.0               1.7
36                 5.5               3.5                1.3               0.2
83                 6.0               2.7                5.1               1.6
60                 5.0               2.0                3.5               1.0
131                7.9               3.8            

In [ ]:
#학습을 위한 학습기 - 알고리즘으로 이루어진 객체
iris_dtc =DecisionTreeClassifier(random_state =20,criterion='gini')
iris_dtc.fit(X_train,y_train)
prediction= iris_dtc.predict(X_test)


#예측 정확도 평가
from sklearn.metrics import accuracy_score
print('예측정확도:{0:.2f}'.format(accuracy_score(y_test, prediction)))

In [61]:
# 학습시킬때 테스트데이터 세트를 이용하지 않고 학습 데이터 세트로만 하급하고 예측한다면?

from sklearn.datasets import load_iris
from sklearn.tree     import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

bad_iris =load_iris()

#데이터 세트 분할없이 얻어오기
train_data =iris.data
train_label=iris.target

# 학습을 위한 분류 모델
bad_iris_clf = DecisionTreeClassifier()
bad_iris_clf.fit(train_data, train_label)


# 잘못된 예측
pred = bad_iris_clf.predict(train_data)
print('예측 정확도: ', accuracy_score(train_label, pred))

예측 정확도:  1.0


## 교차검증

- KFold방식


In [62]:
from sklearn.datasets import load_iris
from sklearn.tree     import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

import pandas as pd
import numpy as np


In [64]:
fold_iris=load_iris()
features =fold_iris.data
#print(features)
label=fold_iris.target
#print(label)
fold_df_clf=DecisionTreeClassifier()

In [76]:
#5개의 폴드 세트를 분리하여 각 폴드 세트별 정확도를 담을 리스트 생성
kfold=KFold(n_splits=5)
cv_accuracy=[]
print('iris shape',features.shape[0])

iris shape 150


In [84]:
n_iter = 0
for train_idx , test_idx in kfold.split(features) :
    #print(train_idx, test_idx)
    X_train , X_test = features[train_idx], features[test_idx]
    #print('X_train\n', X_train)
    #print('X_test\n', X_test)
    y_train, y_test = label[train_idx] , label[test_idx]
    #print('y_train\n', y_train)
    #print('y_test\n', y_test)
    
    # 학습을 진행하겠다면?
    fold_df_clf.fit(X_train, y_train)
    
    # 예측
    fold_pred = fold_df_clf.predict(X_test)
    
    #정확도 측정
    n_iter+=1
    accuracy=np.round (accuracy_score(y_test,fold_pred),4)
    print('\n{}교차검증 정확도 :{},학습데이터 크기:{},검증 데이터 크기:{}'.format(n_iter,accuracy,X_train.shape[0],X_test.shape[0]))
    
    cv_accuracy.append(accuracy)
print('\n\n')                    
    
    
print('\n 평균검증 정확도:', np.mean(cv_accuracy))
    
    


1교차검증 정확도 :1.0,학습데이터 크기:120,검증 데이터 크기:30

2교차검증 정확도 :0.9667,학습데이터 크기:120,검증 데이터 크기:30

3교차검증 정확도 :0.8333,학습데이터 크기:120,검증 데이터 크기:30

4교차검증 정확도 :0.9333,학습데이터 크기:120,검증 데이터 크기:30

5교차검증 정확도 :0.8,학습데이터 크기:120,검증 데이터 크기:30




 평균검증 정확도: 0.9088866666666668


- Stratified KFold:불균형한 분포도를 가진 레이블 데이터 집합을 위한 KFold

- 레이블의 분포를 먼저 고려한뒤 이 분포와 동일하게 학습과 검증 데이터 세트로 분할

In [94]:
# 기존 KFold의 문제점 다시 한번 확인
kfold_iris_data = load_iris()
print('\n\n',kfold_iris_data)

kfold_iris_data_df =pd.DataFrame(data=kfold_iris_data.data,columns=kfold_iris_data.feature_names)
kfold_iris_data_df['target'] =kfold_iris_data.target
print("value_counts:\n", kfold_iris_data_df['target'].value_counts())



 {'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
  

In [95]:
kfold_iris_data_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [93]:
kfold_iris=KFold
cnt_iter=0

for train_idx , test_idx in kfold.split(features) :
    #print(train_idx, test_idx)
    cnt_iter+=1
    label_train = kfold_iris_data_df['target'].iloc[train_idx]
    label_test = kfold_iris_data_df['target'].iloc[test_idx]
    #print('label_train\n',label_train)
    print('교차검증:{}'.format(cnt_iter))
    print('학습 레이블 데이터 분포:\n',label_train.value_counts())
    print('검증 레이블 데이터 분포:\n',label_test.value_counts())

교차검증:1
학습 레이블 데이터 분포:
 2    50
1    50
0    20
Name: target, dtype: int64
검증 레이블 데이터 분포:
 0    30
Name: target, dtype: int64
교차검증:2
학습 레이블 데이터 분포:
 2    50
1    40
0    30
Name: target, dtype: int64
검증 레이블 데이터 분포:
 0    20
1    10
Name: target, dtype: int64
교차검증:3
학습 레이블 데이터 분포:
 2    50
0    50
1    20
Name: target, dtype: int64
검증 레이블 데이터 분포:
 1    30
Name: target, dtype: int64
교차검증:4
학습 레이블 데이터 분포:
 0    50
1    40
2    30
Name: target, dtype: int64
검증 레이블 데이터 분포:
 2    20
1    10
Name: target, dtype: int64
교차검증:5
학습 레이블 데이터 분포:
 1    50
0    50
2    20
Name: target, dtype: int64
검증 레이블 데이터 분포:
 2    30
Name: target, dtype: int64


In [100]:
#레이블 값의 분호를 반영해주지 못하는 문제를 해결하기 위해서 stratifieldKFOld를 이용

from sklearn.model_selection import StratifiedKFold


skf_iris = StratifiedKFold(n_splits=3)
cnt_iter=0

for train_idx , test_idx in skf_iris.split (kfold_iris_data_df, kfold_iris_data_df['target']) :
    #print(train_idx, test_idx)
    cnt_iter+=1
    label_train = kfold_iris_data_df['target'].iloc[train_idx]
    label_test  = kfold_iris_data_df['target'].iloc[test_idx]
    
    
    #print('label_train\n',label_train)
    print('교차검증:{}'.format(cnt_iter))
    print('학습 레이블 데이터 분포:\n',label_train.value_counts())
    print('검증 레이블 데이터 분포:\n',label_test.value_counts())

교차검증:1
학습 레이블 데이터 분포:
 2    33
1    33
0    33
Name: target, dtype: int64
검증 레이블 데이터 분포:
 2    17
1    17
0    17
Name: target, dtype: int64
교차검증:2
학습 레이블 데이터 분포:
 2    33
1    33
0    33
Name: target, dtype: int64
검증 레이블 데이터 분포:
 2    17
1    17
0    17
Name: target, dtype: int64
교차검증:3
학습 레이블 데이터 분포:
 2    34
1    34
0    34
Name: target, dtype: int64
검증 레이블 데이터 분포:
 2    16
1    16
0    16
Name: target, dtype: int64
