# numpy 개념 다지기

In [1]:
import numpy as np

In [6]:
#1차원 
array1= np.array([1,2,3])
print('array1 type',array1.shape)

#2차원 :2개의 로우 3개의 칼럼
array2= np.array([[1,2,3],[2,3,4]])
print('array2 type',array2.shape)

#2차원:1개 로우, 3개 컬럼
array3= np.array([[1,2,3]])
print('array3 type',array3.shape)

array1 type (3,)
array2 type (2, 3)
array3 type (1, 3)


In [13]:
list1=[1,2,3]
print(type(list1))
array1= np.array(list1) #리스트에서 넘파이로 변환
print(type(array1))
print(array1,array1.dtype)
      

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [16]:
#dtype 형변환
array_int=np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float,array_float.dtype)

array_float1=np.array([1.1,1.2,2.3])
array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1. 2. 3.] float64
[1 2 3] int32


### ndarray 편리 하게 생성: arange, zeors, ones

- arange():함수는 인자로 받는 값 만큼 1씩 증가하는 1차원 array를 만든다.
- 이때 하나의 인자만 입력하면 0 ~ 입력한 인자, 값 만큼의 크기를 가진다.




In [21]:
s_array= np.arange(10)
print(s_array)

[0 1 2 3 4 5 6 7 8 9]


- np.zeros() 함수는 인자로 받는 크기만큼, 모든요소가 0인 array를 만든다.



In [23]:
z_array =np.zeros((3,2))
print(z_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


- np.ones() 함수는 인자로 받는 크기만큼, 모든요소가 1인 array를 만든다.


### reshape(): 차원의 크기를 변경

In [27]:
array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### indexing: 원하는 특정데이터만 추출

In [6]:
array1= np.arange(start=1, stop=10)
print(array1)


value=array1[2]
print(value)

value2= array1[2:5]
value2

[1 2 3 4 5 6 7 8 9]
3


array([3, 4, 5])

In [9]:
array1[0]=9
array1

array([9, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
array3=array1[0:3]
array3

array([9, 2, 3])

### sort,argsort(): 행렬의 정렬

In [12]:
org_array =np.array([3,1,9,5])
print('원본행렬:',org_array)

sort_array1 = np.sort(org_array)
print('np.sort()호출 후 반환된 정렬 행렬:', sort_array1)

원본행렬: [3 1 9 5]
np.sort()호출 후 반환된 정렬 행렬: [1 3 5 9]


In [13]:
sort_indices = np.argsort(org_array)
print(sort_indices)

[1 0 3 2]


In [14]:
A= np.array([[1,2,3],[4,5,6]])

B= np.array([[7,8],[9,10],[11,12]])


In [16]:
dot_product= np.dot(A,B)
dot_product

array([[ 58,  64],
       [139, 154]])